stages:
  - build
  - test

build:
  stage: build
  only:
    - tags
  script: 
    - echo "#define VERSION \"$CI_COMMIT_TAG\"" > Marco_Version.h 
    - g++ -c test.cpp
    - g++ -o test test.o
  artifacts:
    paths:
      - test
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  cache:
    paths:
      - "*.o"

# run tests using the binary built before
test:
  stage: test
  only:
    - tags
  script:
    - ./test
    - chmod +x setRelease.sh
    - ./setRelease.sh

